### ISSUE TITLE
Odoo 8 : l10n_be_coda - Coda import - missing items

### ISSUE THREAD

**Issue by yboujraf** [luc-demeyer/noviat-apps#19]
Impacted versions: 8.0.2.1

Steps to reproduce: import coda file

Current behavior: some items are not imported

Expected behavior: all items in the bank statement need to be imported

Video/Screenshot link (optional):

I have an issue with coda import from one specific partner.
When Imported the coda file we have a red color and when opening the coda file a part of the entries are available

![](https://cloud.githubusercontent.com/assets/6151258/19982238/93a9f420-a205-11e6-8ef0-854e6e8721af.png)

All entries from ACERTA aren’t imported.

![](https://cloud.githubusercontent.com/assets/6151258/19982264/b0ff739c-a205-11e6-982f-572bdd5c8749.png)

coda file

[BE54001591120197_EUR_Full_20161006.zip](https://github.com/luc-demeyer/noviat-apps/files/614797/BE54001591120197_EUR_Full_20161006.zip)

Thanks in advance
@yboujraf

**Comment by luc-demeyer** [comment]
Dear,

there are lots of other CODA file elements that are not imported by the coda module that is part of the standard addons. This module is a simplified CODA importer that is derived from the 'l10n_be_coda_advanced module (cf. apps.odoo.com). For complete CODA support with rules engine to fully automate your bank statement operations, you should download this one plus the prerequisite account_bank_statement_advanced module (and read carefully the installation instructions since some patches on the standard bank statement from Odoo are required). 
You should consider the CODA module that is part of the standard addons as a rather simple encoding aid that requires to still have the printed bank statements in order to complete the missing elements.

**Comment by yboujraf** [comment]
Dear Mr Demeyer,

 

Thanks for your support.

 

After installing the coda modules you mentioned, we encourted an error message.

 

May I ask you to support us to fix that?

 

Best Regards

 

Youssef

**Comment by luc-demeyer** [comment]
No problem.

Let me know what the error is and preferably also send me the CODA file so that we can reproduce the error and fix it.

 

Regards,

Luc

 

 

 <http://www.noviat.com/> www.noviat.com

Rusatiralaan 1, 1083 Brussel

+32 2 808 86 38

**Comment by yboujraf** [comment]
Dear

 
Please find the coda file and the screen capture of the error when trying to use your modules.

 For installing the modules, do we need to uninstall the module “l10n_be_coda” before to install the modules “'l10n_be_coda_advanced module”?

Best Regards,

Youssef

**Comment by yboujraf** [comment]
Dear,

Please find the  file.

[BE54001591120197_EUR_Full_20161107.zip](https://github.com/luc-demeyer/noviat-apps/files/626047/BE54001591120197_EUR_Full_20161107.zip)


* The items not imported are from ACERTA.

About 'l10n_be_coda_advanced module' :

Please find the error message when tried to import coda files :

![image001](https://cloud.githubusercontent.com/assets/6151258/20818108/be3a69b8-b82b-11e6-9d93-7c44b9587011.png)

With the standard coda module 'l10n_be_coda' we don't have this error, all the statements are imported and linked with the correct bank account.

Otherwise, may I ask you to give us the step by step to setup those modules  ?

For installing the modules, do we need to uninstall the module “l10n_be_coda” before to install the modules “'l10n_be_coda_advanced module”?

Best Regards,
Youssef

**Comment by luc-demeyer** [comment]
you need to uninstall l10n_be_coda before installing l10n_be_coda_advanced.

config:

![image](https://cloud.githubusercontent.com/assets/7706945/20860820/d9a2246e-b981-11e6-91d4-d6af0d1783c2.png)

**Comment by yboujraf** [comment]
Dear,

STEP 1 : uninstall "l10n_be_coda" module

Successfuly

STEP 2 : install "l10n_be_coda_advanced" module

![image](https://cloud.githubusercontent.com/assets/6151258/20870015/a0231b36-ba7f-11e6-9339-30ed35f6bca3.png)

I got this error message

![image](https://cloud.githubusercontent.com/assets/6151258/20870019/ad9c6952-ba7f-11e6-80f9-7d26f1ab92ab.png)

I hope it will help you

Best Regards,
Youssef

**Comment by luc-demeyer** [comment]
The error message seems sufficiently clear to me: you have already imported (or created manually) a bank statement with the same name as the one you try to import now. 
You can adapt the bank statement naming policy in the coda config to ensure other naming.

**Comment by yboujraf** [comment]
Dear Luc,

Is it possible to reach you by phone ?

Best Regards,
Youssef


*BOUJRAF Youssef | CEO - Managing Director*

Direct Line: +32 (0)2 880 33 30
Mobile: +32 (0)477 94 86 89
Fax: +32 (0)2 318 82 21
Skype: y_boujraf
Email: yboujraf@by-systems.be
Web : www.by-systems.be/
BY-SYSTEMS sprl| Avenue Charles Plisnier 13 | B-1070 Anderlecht | Belgium |
TVA: BE 0819.832.617

This communication, issued by BY-SYSTEMS SPRL, is confidential and we do
not waive confidentiality by mistransmission. If you have received it by
mistake please notify the sender immediately by reply and then delete it
permanently from your system without copying it, using it for any purposes
or disclosing its contents to any other person. Thank you for your
cooperation. Any views expressed in this message are those of the
individual sender and may not necessarily reflect the views of BY-SYSTEMS
SPRL. Emails are not secure and cannot be guaranteed to be error free as
they can be intercepted, amended, lost or destroyed, or contain viruses.
Anyone who communicates with us by email is taken to accept these risks.

2016-12-05 10:32 GMT+01:00 Luc De Meyer <notifications@github.com>:
