### ISSUE TITLE
v10 stock_level_export_xls  - Column Qty x Cost  all zero

### ISSUE THREAD

**Issue by bunhin** [luc-demeyer/noviat-apps#27]
Hi @luc-demeyer 

I just try the stock_level_export_xls,  it works very good but i found the Qty x Cost Column is all zero although the qty column and the cost collumn are not zero on the same row (The add cost was checked in wizard form),  is it a bug or i need to do something to get the column with value?

Thanks,

**Comment by luc-demeyer** [comment]
This column is a formula (qty x cost) hence it is NOT null.
I suppose that you simply need to click on "Enable Editing" on the exported spreadsheet so that the formula gets executed.

**Comment by bunhin** [comment]
Thank you
