### ISSUE TITLE
Fixed Asset XLS Report

### ISSUE THREAD

**Issue by sm2x** [luc-demeyer/noviat-apps#4]
hi luc,
im using noviat's asset management and all is well except the FA XLS Report is not working for me.
im on odoo 8 updated via git, i keep on getting this error msg using latest google-chrome:

Uncaught SyntaxError: Unexpected token T
http://192.168.1.234:8069/web#page=0&limit=80&view_type=list&model=account.analytic.default&menu_id=326&action=415:1

i noticed model=account.analytic.default, is this could be the reason? i dont have analytic accounts defined yet.

TIA

**Comment by luc-demeyer** [comment]
@sm2x 
Tia,
if this issue is still unresolved with the latest version of this module in the OCA repo (cf https://github.com/OCA/account-financial-tools/tree/8.0) than please open an issue on the OCA repo with clear instructions on how to reproduce and I'll create a fix.
